# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidFinishLaunchingNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('0bedee4b679185a2d6f7244b8c832fe8_MjcyNjMxMjAxMy0wOS0xNSAwMzoyODo1Ni4yODA3OTA')
  end)
end
